# Generated by Django 3.1.2 on 2021-12-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('screen_name', models.CharField(choices=[('Proof_master', 'Proof_master'), ('Project_master', 'Project_master'), ('Admin_master', 'Admin_master'), ('RI_master', 'RI_master'), ('Account_master', 'Account_master')], max_length=50, null=True)),
                ('team_name', models.CharField(choices=[('Audit & Compliance', 'Audit & Compliance'), ('Governance', 'Governance'), ('Dev_team', 'Dev_team'), ('BFS', 'BFS'), ('CTU', 'CTU'), ('EM', 'EM'), ('Ins', 'Ins'), ('LS', 'LS'), ('M&E', 'M&E'), ('MFG', 'MFG'), ('O&G', 'O&G'), ('INT', 'INT'), ('OR', 'OR'), ('CIS', 'CIS'), ('AEG', 'AEG'), ('DATA', 'DATA'), ('SAP', 'SAP'), ('DGT', 'DGT'), ('CSGT', 'CSGT'), ('CLD', 'CLD'), ('IIOT', 'IIOT')], max_length=50, null=True)),
                ('spoc_name', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('spoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
