# Generated by Django 3.1.2 on 2021-12-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spoc',
            name='first_name',
        ),
    ]
