# Generated by Django 3.1.2 on 2021-12-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0002_remove_spoc_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spoc',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='spoc',
            name='spoc',
        ),
    ]
