# Generated by Django 3.1.2 on 2021-12-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0004_auto_20211215_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoc',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spoc',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spoc',
            name='team_name',
            field=models.CharField(choices=[('Audit & Compliance', 'Audit & Compliance'), ('Governance', 'Governance'), ('Dev_team', 'Dev_team'), ('DU(BFS)', 'DU(BFS)'), ('DU(CTU)', 'DU(CTU)'), ('DU(EM)', 'DU(EM)'), ('DU(Ins)', 'DU(Ins)'), ('DU(LS)', 'DU(LS)'), ('DU(M&E)', 'DU(M&E)'), ('DU(MFG)', 'DU(MFG)'), ('DU(O&G)', 'DU(O&G)'), ('DU(INT)', 'DU(INT)'), ('PU(OR)', 'PU(OR)'), ('PU(CIS)', 'PU(CIS)'), ('PU(AEG)', 'PU(AEG)'), ('PU(DATA)', 'PU(DATA)'), ('PU(SAP)', 'PU(SAP)'), ('PU(DGT)', 'PU(DGT)'), ('PU(CSGT)', 'PU(CSGT)'), ('PU(CLD)', 'PU(CLD)'), ('PU(IIOT)', 'PU(IIOT)')], max_length=50, null=True),
        ),
    ]
