# Generated by Django 3.2.9 on 2021-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0005_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
