# Generated by Django 3.1.2 on 2021-12-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoc', '0005_auto_20211216_0857'),
        ('spoc', '0006_delete_upload'),
    ]

    operations = [
    ]
